# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Example app
version: "1.3.1"
slug: example
description: Example app
url: "https://github.com/home-assistant/apps-example/tree/main/example"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/app-example"
