name: Doorbell
description: Homeassistant Doorbell Add-On
version: "1.0.0"
slug: doorbell
init: false
discovery:
  - doorbell
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: media
    read_only: False
  - type: data
    read_only: False
  - type: homeassistant_config
    read_only: False
startup: services
boot: manual
ports:
  5000/tcp: 5000
full_access: True
apparmor: False
privileged:
  - SYS_PTRACE
  - SYS_ADMIN
  - SYS_NICE
  - IPC_LOCK
udev: True
hassio_role: default
auth_api: True
hassio_api: True
homeassistant_api: True
stdin: True
audio: False
options:
  loop_duration: 60
  tts_lang: de-DE
  log_level: warning
schema:
  output: str
  loop_duration: int
  tts_lang: list(en-US|en-GB|de-DE|es-ES|fr-FR|it-IT)
  log_level: list(debug|info|warning|error)
